/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'OS-Icon-Set\'">' + entity + '</span>' + html;
	}
	var icons = {
		'osicon-fastforward': '&#xe68d;',
		'osicon-list': '&#xe68e;',
		'osicon-puzzle': '&#xe68f;',
		'osicon-users': '&#xe690;',
		'osicon-pause': '&#xe67f;',
		'osicon-chevron-down': '&#xe680;',
		'osicon-chevron-left': '&#xe681;',
		'osicon-chevron-right': '&#xe682;',
		'osicon-chevron-top': '&#xe683;',
		'osicon-minus': '&#xe685;',
		'osicon-volume0': '&#xe686;',
		'osicon-volume1': '&#xe687;',
		'osicon-volume2': '&#xe688;',
		'osicon-volume3': '&#xe689;',
		'osicon-delete': '&#xe656;',
		'osicon-tick-circle': '&#xe658;',
		'osicon-windows': '&#xe64e;',
		'osicon-microphone': '&#xe67e;',
		'osicon-desktop': '&#xe65a;',
		'osicon-phone': '&#xe67c;',
		'osicon-tablet': '&#xe67d;',
		'osicon-tree-collapsed': '&#xe699;',
		'osicon-tree-expanded': '&#xe69a;',
		'osicon-drag-handle': '&#xe698;',
		'osicon-arrow-triangle-down': '&#xe694;',
		'osicon-arrow-triangle-left': '&#xe695;',
		'osicon-arrow-triangle-right': '&#xe696;',
		'osicon-arrow-triangle-up': '&#xe697;',
		'osicon-error': '&#xe693;',
		'osicon-ribbon': '&#xe68c;',
		'osicon-arrow-block-right': '&#xe68a;',
		'osicon-open-in-browser': '&#xe68b;',
		'osicon-mail-line': '&#xe684;',
		'osicon-edit-field': '&#xe674;',
		'osicon-filter': '&#xe675;',
		'osicon-join-full-outer': '&#xe676;',
		'osicon-join-inner': '&#xe677;',
		'osicon-join-left-outer': '&#xe678;',
		'osicon-join': '&#xe679;',
		'osicon-order-decreasing': '&#xe67a;',
		'osicon-order-increasing': '&#xe67b;',
		'osicon-info': '&#xe662;',
		'osicon-tooltip': '&#xe608;',
		'osicon-function': '&#xe66d;',
		'osicon-outsystems-logo': '&#xe66e;',
		'osicon-package': '&#xe66f;',
		'osicon-stop': '&#xe670;',
		'osicon-warning': '&#xe671;',
		'osicon-trash': '&#xe672;',
		'osicon-data': '&#xe673;',
		'osicon-archive': '&#xe66c;',
		'osicon-image': '&#xe66b;',
		'osicon-bubble': '&#xe65d;',
		'osicon-cog': '&#xe65e;',
		'osicon-cogs': '&#xe65f;',
		'osicon-eye': '&#xe660;',
		'osicon-heart': '&#xe661;',
		'osicon-link': '&#xe663;',
		'osicon-note': '&#xe664;',
		'osicon-overview': '&#xe665;',
		'osicon-pin': '&#xe666;',
		'osicon-star': '&#xe667;',
		'osicon-thumb-down': '&#xe668;',
		'osicon-thumb-up': '&#xe669;',
		'osicon-url': '&#xe66a;',
		'osicon-clock': '&#xe65c;',
		'osicon-forum': '&#xe65b;',
		'osicon-drop-down': '&#xe657;',
		'osicon-tick': '&#xe659;',
		'osicon-nbr5': '&#xe651;',
		'osicon-nbr4': '&#xe652;',
		'osicon-nbr3': '&#xe653;',
		'osicon-nbr2': '&#xe654;',
		'osicon-nbr1': '&#xe655;',
		'osicon-subscriptions': '&#xe650;',
		'osicon-linux': '&#xe64f;',
		'osicon-world': '&#xe600;',
		'osicon-webinar': '&#xe601;',
		'osicon-visual-dev': '&#xe602;',
		'osicon-user': '&#xe603;',
		'osicon-twitter': '&#xe604;',
		'osicon-triangle-more': '&#xe605;',
		'osicon-triangle-less': '&#xe606;',
		'osicon-transportation': '&#xe607;',
		'osicon-telephone': '&#xe609;',
		'osicon-technology': '&#xe60a;',
		'osicon-tag': '&#xe60b;',
		'osicon-share': '&#xe60c;',
		'osicon-security': '&#xe60d;',
		'osicon-secure-portfolio': '&#xe60e;',
		'osicon-search': '&#xe60f;',
		'osicon-science': '&#xe610;',
		'osicon-quote': '&#xe611;',
		'osicon-plus': '&#xe612;',
		'osicon-play': '&#xe613;',
		'osicon-play-triangle': '&#xe614;',
		'osicon-pdf': '&#xe615;',
		'osicon-outsystems': '&#xe616;',
		'osicon-oshome': '&#xe617;',
		'osicon-news': '&#xe618;',
		'osicon-net': '&#xe619;',
		'osicon-microscope': '&#xe61a;',
		'osicon-menu': '&#xe61b;',
		'osicon-megaphone': '&#xe61c;',
		'osicon-manage': '&#xe61d;',
		'osicon-maintenance': '&#xe61e;',
		'osicon-mail': '&#xe61f;',
		'osicon-logout': '&#xe620;',
		'osicon-login': '&#xe621;',
		'osicon-linkedin': '&#xe622;',
		'osicon-leader': '&#xe623;',
		'osicon-java': '&#xe624;',
		'osicon-integration': '&#xe625;',
		'osicon-insurance': '&#xe626;',
		'osicon-increase': '&#xe627;',
		'osicon-idea': '&#xe628;',
		'osicon-home-banking': '&#xe629;',
		'osicon-healthcare': '&#xe62a;',
		'osicon-guide': '&#xe62b;',
		'osicon-google': '&#xe62c;',
		'osicon-folder': '&#xe62d;',
		'osicon-facebook': '&#xe62e;',
		'osicon-environment': '&#xe62f;',
		'osicon-environment-add': '&#xe630;',
		'osicon-enterprise': '&#xe631;',
		'osicon-energy': '&#xe632;',
		'osicon-edit': '&#xe633;',
		'osicon-download': '&#xe634;',
		'osicon-document': '&#xe635;',
		'osicon-devops': '&#xe636;',
		'osicon-desktop-mobile': '&#xe637;',
		'osicon-deployment': '&#xe638;',
		'osicon-database': '&#xe639;',
		'osicon-dashboard': '&#xe63a;',
		'osicon-create-user': '&#xe63b;',
		'osicon-create-app': '&#xe63c;',
		'osicon-community': '&#xe63d;',
		'osicon-cloud': '&#xe63e;',
		'osicon-cloud-outline': '&#xe63f;',
		'osicon-cloud-on-premises': '&#xe640;',
		'osicon-close': '&#xe641;',
		'osicon-chevron': '&#xe642;',
		'osicon-chevron-circle': '&#xe643;',
		'osicon-change': '&#xe644;',
		'osicon-buoy': '&#xe645;',
		'osicon-arrow-up': '&#xe646;',
		'osicon-arrow-right': '&#xe647;',
		'osicon-arrow-left': '&#xe648;',
		'osicon-arrow-down': '&#xe649;',
		'osicon-architecture': '&#xe64a;',
		'osicon-academy': '&#xe64b;',
		'osicon-1-click-publish': '&#xe64c;',
		'osicon-1-click-publish-outline': '&#xe64d;',
		'osicon-asap': '&#xe69d;',
		'osicon-browser': '&#xe69e;',
		'osicon-calendar': '&#xe69f;',
		'osicon-calendarplus': '&#xe6a0;',
		'osicon-check-full': '&#xe6a1;',
		'osicon-checklist': '&#xe6a2;',
		'osicon-complex': '&#xe6a3;',
		'osicon-group': '&#xe6a4;',
		'osicon-meeting': '&#xe6a5;',
		'osicon-nodata': '&#xe6a6;',
		'osicon-partners': '&#xe6a7;',
		'osicon-people': '&#xe6a8;',
		'osicon-peopleplus': '&#xe6a9;',
		'osicon-peopletons': '&#xe6aa;',
		'osicon-piechart': '&#xe6ab;',
		'osicon-screens': '&#xe6ac;',
		'osicon-screensplus': '&#xe6ad;',
		'osicon-screenstons': '&#xe6ae;',
		'osicon-validation': '&#xe6af;',
		'osicon-worldfull': '&#xe6b0;',
		'osicon-nolockin': '&#xe69b;',
		'osicon-apple': '&#xe691;',
		'osicon-android': '&#xe692;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/osicon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
